# Site settings
title: Stanton Recipes
email: your-email@domain.com
description: Recipes that we love. Make them and share the good word.
baseurl: "https://recipes.stanton.io"
language: "en"
lang_direction: "ltr"
color: "#b1A296"

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
